Add valid
SkorokhodovSemen/java-shareit pull request #2
Opened 2024-01-22 12:27 UTC by SkorokhodovSemen

2024-01-22 12:30 UTC, SkorokhodovSemen commented
Тесты не пройдут из-за другого названия ветки
Добавил стандартную валидацию на уровне контроллера
Встрял на добавлении валидации для проверки с полями, которые берутся из репозитория (на проверку такой же почты, на проверку поиска) Но по идеи, это уже не ошибки validation, а ошибки conflict и NotFound

Их так и оставляют или пишут свои валидаторы? Если свои - то хорошую бы статью найти, а то в интернете много разного

2024-01-23 07:11 UTC, VadimZharkov commented
> Тесты не пройдут из-за другого названия ветки Добавил стандартную валидацию на уровне контроллера Встрял на добавлении валидации для проверки с полями, которые берутся из репозитория (на проверку такой же почты, на проверку поиска) Но по идеи, это уже не ошибки validation, а ошибки conflict и NotFound
> 
> Их так и оставляют или пишут свои валидаторы? Если свои - то хорошую бы статью найти, а то в интернете много разного

Для проверки полей кторым потребуется обратиться к репозиторию используем обычные методы, аннотации здесь никак не помогут

2024-01-23 07:13 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotNull(message = "Пользователь не заполнил поле name")
`@NotNull` избыточно использовать, когда есть `@NotBlank`
`@NotBlank`  содержит в себе  `@NotNull`

2024-01-23 07:14 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +public class UserDto {
Тоже самое про NotNull

2024-01-23 07:15 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto updateUser(@PathVariable("userId") long userId, @RequestBody UserDto userDto) {
Здесь тоже нужно `@Valid` добавить

2024-01-23 07:17 UTC, VadimZharkov requested changes
Еще пару моментов подправить

2024-01-23 08:59 UTC, SkorokhodovSemen commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto updateUser(@PathVariable("userId") long userId, @RequestBody UserDto userDto) {
В методе Patch, в тестах могу приходить поля с null, поэтому проверять сам объект на все поля в контроллере не получится, из-за чего тесты валятся.
Поэтому в классе сервисе, я проверяю наличие полей, и в зависимости от того или иного значения поля вызываю различные методы репозитория. 
Там может прийти только поле name или только поле email, или оба поля сразу.

2024-01-23 09:00 UTC, SkorokhodovSemen commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto updateUser(@PathVariable("userId") long userId, @RequestBody UserDto userDto) {
![image](https://github.com/SkorokhodovSemen/java-shareit/assets/80544964/dfd19fee-61b0-4285-a49d-0640d81e8c9d)

2024-01-23 09:04 UTC, SkorokhodovSemen commented
Написал свой комментарий к @Valid

2024-01-23 16:08 UTC, VadimZharkov commented
> Написал свой комментарий к @Valid

Для таких случаев есть так называемая group-level validation @Validated, должны давать вроде бы
https://www.baeldung.com/spring-valid-vs-validated

можно будет в след работе применить

2024-01-23 16:09 UTC, VadimZharkov approved these changes

2024-01-24 09:41 UTC, closed without merging