Create: DB, booking, comment
SkorokhodovSemen/java-shareit pull request #3
Opened 2024-02-09 11:11 UTC by SkorokhodovSemen

Тесты очень смущали названием своих полей, пришлось делать дополнительные DTO классы.
Сделал много валидаций, не знаю, корректно так или можно было по другому.
Кажется намудрил с последним и следующим бронированием, но сделал как сделал. Если подскажешь как правильно, то сделаю.

2024-02-10 08:15 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/config/PersistenceConfig.java
> +    private Properties hibernateProperties() {
Необязательно было делать конфиг, все свойства можно было прописать в application.properties

2024-02-10 08:18 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/User.java
>  public class User {
Нужно единообразно с item поместить в пакет model

2024-02-10 08:20 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/dto/BookingItem.java
> +public class BookingItem {
Нужно добавить суффикс Dto

2024-02-10 08:21 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>      @AssertTrue(message = "Пользователь не заполнил поле available")
Бессмысленная аннотация, примитивный тип boolean будет заполнен всегда значением по умолчанию

2024-02-10 08:26 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        switch (state) {
Лучше сделать перечислимое

2024-02-10 08:29 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        validFoundForUser(userOptional, idUser);
Да с методами valid перебор)
Лучше например так 
```
		userRepository.findById(userId)
				.orElseThrow(() -> new IllegalStateException("Wrong user id=" + userId));
```

2024-02-10 08:33 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +public interface CommentRepository extends JpaRepository<Comment, Long>, QuerydslPredicateExecutor<Comment> {
Не нашел применения QuerydslPredicateExecutor

2024-02-10 08:46 UTC, VadimZharkov commented on src/main/resources/schema.sql
> +
Нужно отформатировать код, добавить по строчке межу операторами. В текущем виде читать код практически не возможно.

2024-02-10 08:49 UTC, VadimZharkov requested changes
Можно улучшить

2024-02-11 07:41 UTC, SkorokhodovSemen commented on src/main/java/ru/practicum/shareit/config/PersistenceConfig.java
> +    private Properties hibernateProperties() {
Нам целый спринт объясняли как этот файл делать, я и подумал, что надо через него...

2024-02-11 07:44 UTC, SkorokhodovSemen commented on src/main/java/ru/practicum/shareit/user/User.java
>  public class User {
Сделал рефакторинг

2024-02-11 07:44 UTC, SkorokhodovSemen commented on src/main/java/ru/practicum/shareit/item/dto/BookingItem.java
> +public class BookingItem {
Готово

2024-02-11 07:45 UTC, SkorokhodovSemen commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>      @AssertTrue(message = "Пользователь не заполнил поле available")
Готово

2024-02-11 07:47 UTC, SkorokhodovSemen commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +public interface CommentRepository extends JpaRepository<Comment, Long>, QuerydslPredicateExecutor<Comment> {
Видимо на автомате уже

2024-02-11 07:56 UTC, SkorokhodovSemen commented on src/main/resources/schema.sql
> +
Я не знаю почему, но когда я разделяю текст по каждому оператору с новой строки, то у меня выбрасывается ошибка SQL, что он не может выполнить шаблон данной схемы...

2024-02-11 08:16 UTC, SkorokhodovSemen commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        switch (state) {
Готово

2024-02-11 15:36 UTC, VadimZharkov reviewed
Повторюсь про QuerydslPredicateExecutor. Не нашел использования предикатов в классах сервисах. Зачем почти все репозитории наследуются от QuerydslPredicateExecutor?

2024-02-11 15:38 UTC, VadimZharkov commented on src/main/resources/schema.sql
> +
Пример как должен оформляться код SQL

```
CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (user_id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
  item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255),
  description VARCHAR(4000),
  available BOOLEAN,
  owner_id BIGINT NOT NULL,
  CONSTRAINT pk_item PRIMARY KEY (item_id),
  CONSTRAINT FK_ITEM_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (user_id),
  CONSTRAINT UQ_OWNER_ITEM_NAME UNIQUE(owner_id, name)
);
```

2024-02-11 15:42 UTC, VadimZharkov requested changes
Нужно еще доработать

2024-02-11 16:39 UTC, SkorokhodovSemen commented on src/main/resources/schema.sql
> +
Я прекрасно с 1 раза понял, но объясните мне почему при запуске кода он не воспринимает этот файл и выдает ошибки в sql выражении???
![image](https://github.com/SkorokhodovSemen/java-shareit/assets/80544964/53c62ed8-4777-49fc-96b4-3577b4b9ea61)

2024-02-11 20:09 UTC, SkorokhodovSemen commented on src/main/resources/schema.sql
> +
Короче, после нескольких часов мучений и советов от старшего наставника, так и не поняли в чем была ошибка.
Удалил конфиг, поменял настройки и pom и все заработало

2024-02-12 06:10 UTC, VadimZharkov approved these changes

2024-02-12 14:00 UTC, merged