Create: Docker, postgres DB
SkorokhodovSemen/java-shareit pull request #6
Opened 2024-03-09 13:53 UTC by SkorokhodovSemen

2024-03-09 16:15 UTC, SkorokhodovSemen commented
Почему-то тесты, написанные в прошлом ТЗ не давали мне здесь на гит все пройти
Локально завершается полностью, на гит пишет что есть предупреждения

Удалил, загрузил и все работает...
Может ты сможешь помочь мне разобраться с этим

![image](https://github.com/SkorokhodovSemen/java-shareit/assets/80544964/abf60b67-df40-4913-93cb-c7e5f60c5557)
![image (1)](https://github.com/SkorokhodovSemen/java-shareit/assets/80544964/35297ade-5314-4cfc-b87e-72828f4bc3cd)

2024-03-09 17:21 UTC, SkorokhodovSemen commented
Захотел проверить 1 теорию с тестами, не получилось, так и выдает error. Поэтому удалил

2024-03-10 06:50 UTC, VadimZharkov commented on gateway/src/main/java/ru/practicum/shareit/user/dto/Create.java
Нет необходимости для каждого класса Dto делать отдельный интерфейс-маркер подобный Create. Достаточно одного для всех Dto

2024-03-10 06:54 UTC, VadimZharkov commented on server/pom.xml
> +		<dependency>
В сервере этой зависимости быть уже не должно, только в гейтвай

2024-03-10 06:57 UTC, VadimZharkov commented on server/src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
checkCorrectTime относится к валидации параметров Dto. Поэтому логично размесить данную проверку в гейтвай и не пропускать невалидные Dto в server

2024-03-10 06:58 UTC, VadimZharkov requested changes
Можно улучшить

2024-03-10 07:28 UTC, SkorokhodovSemen commented on gateway/src/main/java/ru/practicum/shareit/user/dto/Create.java
Вынес в отдельный пакет marker и удалил лишние

2024-03-10 07:29 UTC, SkorokhodovSemen commented on server/pom.xml
> +		<dependency>
Удалил, но не понятно, почему

2024-03-10 07:48 UTC, SkorokhodovSemen commented on server/src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
Сделал свою валидацию, в новую папку и интерфейсы закинул

2024-03-11 06:02 UTC, VadimZharkov commented on server/pom.xml
> +		<dependency>
я про jakarta.validation

2024-03-11 06:09 UTC, VadimZharkov approved these changes

2024-03-11 06:10 UTC, VadimZharkov approved these changes

2024-05-13 10:46 UTC, closed without merging